preloader: build/spm build/spm/preloader.bin
build/spm/preloader.bin: source/preloader/preloader.s
	$(ASSEMBLER) -mbroadway $< -o $@.o -Isource/preloader
	$(LINKER) -T linker/asm_to_binary.ld $@.o -o $@
	rm $@.o
	touch $@
